# Generated by Django 4.0.3 on 2022-03-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mName', models.CharField(max_length=20)),
                ('mLast', models.CharField(max_length=20)),
                ('mFirst', models.CharField(max_length=20)),
                ('mPersonid', models.CharField(max_length=20)),
                ('mPhone', models.CharField(max_length=50)),
                ('mBirthday', models.DateField()),
                ('mSex', models.CharField(default='M', max_length=2)),
                ('mEmail', models.EmailField(max_length=100)),
                ('mPassword', models.CharField(max_length=50)),
                ('mCard', models.CharField(max_length=20)),
                ('mSafe', models.CharField(max_length=5)),
                ('creditmonth', models.IntegerField()),
                ('credityear', models.IntegerField()),
                ('creditName', models.CharField(max_length=20)),
            ],
        ),
    ]
