# Generated by Django 4.0.3 on 2022-03-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='mAddress',
            field=models.CharField(default='假地址', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='mCity',
            field=models.CharField(default='新北市', max_length=20),
        ),
    ]
