# Generated by Django 4.0.3 on 2022-03-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_member_maddress_member_mcity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mBirthday',
            field=models.DateField(default='2022/03/28'),
        ),
    ]
