# Generated by Django 4.0.3 on 2022-03-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_alter_member_mbirthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='postalCode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='mAddress',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='mCity',
            field=models.CharField(default='', max_length=20),
        ),
    ]
