# Generated by Django 4.0.3 on 2022-03-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_member_postalcode_alter_member_maddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mBirthday',
            field=models.DateField(default='2022/03/29'),
        ),
    ]
