# Generated by Django 4.0.3 on 2022-04-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0006_alter_member_postalcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nickname',
            field=models.CharField(default=0.1115401310403149, max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='mBirthday',
            field=models.DateField(default='2022/04/03'),
        ),
    ]
